### ISSUE TITLE
"cpan -i HTML::Tidy" on a fresh perl installs fails tests due to missing Test::Exception

### ISSUE THREAD

**Issue by shlomif** [petdance/html-tidy#28]
Hi!

With bleadperl and HTML-Tidy-1.60 I am getting this:

```
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/shlomif/.cpan/Metadata'
  Database was generated on Fri, 08 Sep 2017 16:41:03 GMT
CPAN: Time::HiRes loaded ok (v1.9743)
CPAN: HTTP::Tiny loaded ok (v0.070)
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/shlomif/.cpan/sources/authors/01mailrc.txt.gz'
CPAN: Compress::Zlib loaded ok (v2.074)
............................................................................DONE
Fetching with HTTP::Tiny:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/shlomif/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Wed, 13 Sep 2017 18:53:54 GMT
  HTTP::Date not available
............................................................................DONE
Fetching with HTTP::Tiny:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/shlomif/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/shlomif/.cpan/Metadata
Running install for module 'HTML::Tidy'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/P/PE/PETDANCE/HTML-Tidy-1.60.tar.gz
CPAN: Digest::SHA loaded ok (v5.96)
Warning (usually harmless): 'YAML' not installed, cannot parse '/home/shlomif/.cpan/FTPstats.yml'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/P/PE/PETDANCE/CHECKSUMS
Checksum for /home/shlomif/.cpan/sources/authors/id/P/PE/PETDANCE/HTML-Tidy-1.60.tar.gz ok
CPAN: Archive::Tar loaded ok (v2.26)
HTML-Tidy-1.60/
HTML-Tidy-1.60/t/
HTML-Tidy-1.60/t/roundtrip.t
HTML-Tidy-1.60/t/parse.t
HTML-Tidy-1.60/t/wordwrap.cfg
HTML-Tidy-1.60/t/segfault-form.t
HTML-Tidy-1.60/t/cfg-for-parse.cfg
HTML-Tidy-1.60/t/perfect.t
HTML-Tidy-1.60/t/unicode-nbsp.t
HTML-Tidy-1.60/t/wordwrap.t
HTML-Tidy-1.60/t/clean.t
HTML-Tidy-1.60/t/simple.t
HTML-Tidy-1.60/t/ignore.t
HTML-Tidy-1.60/t/venus.t
HTML-Tidy-1.60/t/ignore-text.t
HTML-Tidy-1.60/t/illegal-options.t
HTML-Tidy-1.60/t/unicode.t
HTML-Tidy-1.60/t/unicode.html
HTML-Tidy-1.60/t/too-many-titles.t
HTML-Tidy-1.60/t/pod.t
HTML-Tidy-1.60/t/levels.t
HTML-Tidy-1.60/t/version.t
HTML-Tidy-1.60/t/opt-00.t
HTML-Tidy-1.60/t/message.t
HTML-Tidy-1.60/t/venus.html
HTML-Tidy-1.60/t/cfg-for-parse.t
HTML-Tidy-1.60/t/extra-quote.t
HTML-Tidy-1.60/t/00-load.t
HTML-Tidy-1.60/t/venus.cfg
HTML-Tidy-1.60/t/parse-errors.t
HTML-Tidy-1.60/t/pod-coverage.t
HTML-Tidy-1.60/t/clean-crash.t
HTML-Tidy-1.60/perlcriticrc
HTML-Tidy-1.60/bin/
HTML-Tidy-1.60/bin/webtidy
HTML-Tidy-1.60/ppport.h
HTML-Tidy-1.60/Changes
HTML-Tidy-1.60/lib/
HTML-Tidy-1.60/lib/HTML/
HTML-Tidy-1.60/lib/HTML/Tidy.pm
HTML-Tidy-1.60/lib/HTML/Tidy/
HTML-Tidy-1.60/lib/HTML/Tidy/Message.pm
HTML-Tidy-1.60/Makefile.PL
HTML-Tidy-1.60/README.markdown
HTML-Tidy-1.60/MANIFEST
HTML-Tidy-1.60/Tidy.xs
HTML-Tidy-1.60/META.yml
HTML-Tidy-1.60/META.json
'YAML' not installed, will not store persistent state
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
CPAN: CPAN::Meta loaded ok (v2.150010)
CPAN: Module::CoreList loaded ok (v5.20170920)
Configuring P/PE/PETDANCE/HTML-Tidy-1.60.tar.gz with Makefile.PL
Alien::Tidyp not found. Looking for for tidyp on your system.

NOTE: It seems that you don't have LWP::Simple installed.
      The webtidy program will not be able to retrieve web pages.

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for HTML::Tidy
Writing MYMETA.yml and MYMETA.json
  PETDANCE/HTML-Tidy-1.60.tar.gz
  /home/shlomif/apps/perl/bleadperl/bin/perl5.27.4 Makefile.PL -- OK
Running make for P/PE/PETDANCE/HTML-Tidy-1.60.tar.gz
cp lib/HTML/Tidy.pm blib/lib/HTML/Tidy.pm
cp lib/HTML/Tidy/Message.pm blib/lib/HTML/Tidy/Message.pm
Running Mkbootstrap for Tidy ()
chmod 644 "Tidy.bs"
"/home/shlomif/apps/perl/bleadperl/bin/perl5.27.4" -MExtUtils::Command::MM -e 'cp_nonempty' -- Tidy.bs blib/arch/auto/HTML/Tidy/Tidy.bs 644
"/home/shlomif/apps/perl/bleadperl/bin/perl5.27.4" "/home/shlomif/apps/perl/bleadperl/lib/5.27.4/ExtUtils/xsubpp"  -typemap '/home/shlomif/apps/perl/bleadperl/lib/5.27.4/ExtUtils/typemap'  Tidy.xs > Tidy.xsc
mv Tidy.xsc Tidy.c
cc -c  -I. -I/usr/include/tidyp -I/usr/local/include/tidyp -I/usr/include/tidyp -Wall -Wextra -Wformat -Werror=format-security -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O3 -march=native -flto -ffat-lto-objects   -DVERSION=\"1.60\" -DXS_VERSION=\"1.60\" -fPIC "-I/home/shlomif/apps/perl/bleadperl/lib/5.27.4/x86_64-linux/CORE"   Tidy.c
In file included from /usr/include/tidyp/tidyp.h:63:0,
                 from Tidy.xs:5:
/usr/include/tidyp/platform.h:588:0: warning: "__attribute__warn_unused_result__" redefined
 #define __attribute__warn_unused_result__ __attribute__((__warn_unused_result__))
 
In file included from Tidy.xs:2:0:
/home/shlomif/apps/perl/bleadperl/lib/5.27.4/x86_64-linux/CORE/perl.h:3628:0: note: this is the location of the previous definition
 #  define __attribute__warn_unused_result__ __attribute__((warn_unused_result))
 
rm -f blib/arch/auto/HTML/Tidy/Tidy.so
LD_RUN_PATH="/lib/../lib64" cc  -shared -O3 -march=native -flto -ffat-lto-objects -L/usr/local/lib -fstack-protector-strong  Tidy.o  -o blib/arch/auto/HTML/Tidy/Tidy.so  \
   -L/usr/lib -L/usr/local/lib -ltidyp   \
  
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
chmod 755 blib/arch/auto/HTML/Tidy/Tidy.so
cp bin/webtidy blib/script/webtidy
"/home/shlomif/apps/perl/bleadperl/bin/perl5.27.4" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/webtidy
  PETDANCE/HTML-Tidy-1.60.tar.gz
  /usr/bin/make -- OK
Running make test
"/home/shlomif/apps/perl/bleadperl/bin/perl5.27.4" -MExtUtils::Command::MM -e 'cp_nonempty' -- Tidy.bs blib/arch/auto/HTML/Tidy/Tidy.bs 644
PERL_DL_NONLAZY=1 "/home/shlomif/apps/perl/bleadperl/bin/perl5.27.4" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
# Testing HTML::Tidy 1.60, tidyp 1.04, Perl 5.027004, /home/shlomif/apps/perl/bleadperl/bin/perl5.27.4
t/00-load.t .......... ok
t/cfg-for-parse.t .... ok
t/clean-crash.t ...... ok
Can't locate Test/Exception.pm in @INC (you may need to install the Test::Exception module) (@INC contains: /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/lib /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/arch /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4 /home/shlomif/apps/perl/bleadperl/lib/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/5.27.4) at t/clean.t line 6.
BEGIN failed--compilation aborted at t/clean.t line 6.
t/clean.t ............ 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/extra-quote.t ...... ok
t/ignore-text.t ...... ok
t/ignore.t ........... ok
Can't locate Test/Exception.pm in @INC (you may need to install the Test::Exception module) (@INC contains: /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/lib /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/arch /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4 /home/shlomif/apps/perl/bleadperl/lib/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/5.27.4) at t/illegal-options.t line 6.
BEGIN failed--compilation aborted at t/illegal-options.t line 6.
t/illegal-options.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/levels.t ........... ok
t/message.t .......... ok
t/opt-00.t ........... ok
Can't locate Test/Exception.pm in @INC (you may need to install the Test::Exception module) (@INC contains: /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/lib /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/arch /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4 /home/shlomif/apps/perl/bleadperl/lib/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/5.27.4) at t/parse-errors.t line 6.
BEGIN failed--compilation aborted at t/parse-errors.t line 6.
t/parse-errors.t ..... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Can't locate Test/Exception.pm in @INC (you may need to install the Test::Exception module) (@INC contains: /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/lib /home/shlomif/.cpan/build/HTML-Tidy-1.60-0/blib/arch /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/site_perl/5.27.4 /home/shlomif/apps/perl/bleadperl/lib/5.27.4/x86_64-linux /home/shlomif/apps/perl/bleadperl/lib/5.27.4) at t/parse.t line 6.
BEGIN failed--compilation aborted at t/parse.t line 6.
t/parse.t ............ 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/perfect.t .......... ok
t/pod-coverage.t ..... skipped: Test::Pod::Coverage 1.04 required for testing POD coverage
t/pod.t .............. skipped: Test::Pod 1.14 required for testing POD
t/roundtrip.t ........ ok
t/segfault-form.t .... ok
t/simple.t ........... ok
t/too-many-titles.t .. ok
t/unicode-nbsp.t ..... ok
t/unicode.t .......... ok
t/venus.t ............ ok
t/version.t .......... ok
t/wordwrap.t ......... ok

Test Summary Report
-------------------
t/clean.t          (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/illegal-options.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/parse-errors.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/parse.t          (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=25, Tests=65,  1 wallclock secs ( 0.07 usr  0.01 sys +  0.85 cusr  0.09 csys =  1.02 CPU)
Result: FAIL
Failed 4/25 test programs. 0/65 subtests failed.
Makefile:1081: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
  PETDANCE/HTML-Tidy-1.60.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports PETDANCE/HTML-Tidy-1.60.tar.gz
```

It likely is the cause of this travis-CI failure: https://travis-ci.org/shlomif/perl-begin/builds/274286784 .

Please look into fixing it and let me know if I can help in any way.

**Comment by petdance** [comment]
Fixed in dev 49ec2ea

**Comment by shlomif** [comment]
Hi!

The cpan command still fails because a new version was not uploaded to CPAN. Please fix it there, because this was the whole point of filing this issue. Thanks!

**Comment by shlomif** [comment]
@petdance : ping!

**Comment by petdance** [comment]
This will probably not get released in a while.  It's way way down on my list of priorities.

**Comment by shlomif** [comment]
@petdance : thanks for the comment. I guess I'll add the "install the prereq first" workaround to the CI files.
